kernel_not_configured := $(wildcard kernel/.config)

rowboat: sgx

### DO NOT EDIT THIS FILE ###
include build/core/main.mk
### DO NOT EDIT THIS FILE ###

kernel: droid
ifeq ($(strip $(kernel_not_configured)),)
ifeq ($(TARGET_PRODUCT), beagleboard)
	make -C kernel ARCH=arm omap3_beagle_android_defconfig
endif
ifeq ($(TARGET_PRODUCT), omap3evm)
	make -C kernel ARCH=arm omap3_evm_android_defconfig
endif
ifeq ($(TARGET_PRODUCT), igepv2)
	make -C kernel ARCH=arm igep0020_android_defconfig
endif
ifeq ($(TARGET_PRODUCT), am3517evm)
        make -C kernel ARCH=arm am3517_evm_android_defconfig
endif
endif
	make -C kernel ARCH=arm CROSS_COMPILE=../$($(combo_target)TOOLS_PREFIX) uImage

kernel_clean:
	make -C kernel ARCH=arm clean
	rm kernel/.config

sgx: kernel
	make -C external/ti_android_sgx_sdk ANDROID_ROOT_DIR=`pwd` TOOLS_PREFIX=$($(combo_target)TOOLS_PREFIX) 

sgx_clean: 
	make -C external/ti_android_sgx_sdk clean

rowboat_clean: clean sgx_clean kernel_clean
